# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Mcpdef < Formula
  desc "Fast, self-hostable, single-binary MCP gateway & governance plane"
  homepage "https://github.com/lucheeseng827/mcpdef"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-aarch64-apple-darwin.tar.gz"
      sha256 "c9404505614ab2b9e2992fadf500c165597979973977b8bf8b550b955aeb6f3c"
    end
    on_intel do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-x86_64-apple-darwin.tar.gz"
      sha256 "3163e42df60d48b2f48b1ef947ab3f08a1adc4f635830b732801b5a9f8f5ea63"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7fef16f1c48a1ae1da1a72925291b2b1e3fb0419fa8c121df2e47f49266ea074"
    end
    on_intel do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-x86_64-unknown-linux-musl.tar.gz"
      sha256 "30261912514e9506509dff1698e9e6699761ea80649825415d22a3e029d0a1c3"
    end
  end

  def install
    bin.install "mcpdef"
  end

  test do
    assert_match "mcpdef", shell_output("#{bin}/mcpdef version")
  end
end
