# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Mcpdef < Formula
  desc "Fast, self-hostable, single-binary MCP gateway & governance plane"
  homepage "https://github.com/lucheeseng827/mcpdef"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-aarch64-apple-darwin.tar.gz"
      sha256 "ed29f218d12be61a8baf8f94480fd9610861ed39f923acea3ded0b20128fb345"
    end
    on_intel do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-x86_64-apple-darwin.tar.gz"
      sha256 "8e71b9d7bf4cb72e79b13b9d2dfd5740e083b4ab1a59929c2ce08fdd2322e744"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-aarch64-unknown-linux-musl.tar.gz"
      sha256 "830206f9b917846913290c3d0c75d905aec6c3849fcbcf8170e7c7108ae8f26e"
    end
    on_intel do
      url "https://github.com/lucheeseng827/mcpdef/releases/download/v#{version}/mcpdef-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2df4b8589e2aacb073d0c5a96113737cb1d2897de21b941cc6a18bdb633e85b4"
    end
  end

  def install
    bin.install "mcpdef"
  end

  test do
    assert_match "mcpdef", shell_output("#{bin}/mcpdef version")
  end
end
